baseURL = "hoge"
languageCode = "ja-JP"
title = "poyo"
theme = "minimal"
publishDir = "docs"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""
copyright = "Copyleft; 2017-2017, BrownieAlice. All rights reversed."
