version: 2.1
jobs:
  build:
      docker:
      - image: cibuilds/hugo:latest
      working_directory: ~/work
      steps:
      - add_ssh_keys:
          fingerprints:
              - "56:a6:e1:44:a5:bb:2d:d2:19:19:4c:cf:af:7e:0b:7b"
      - run:
          name: clone
          command: |
                git clone git@github.com:hrichii/sample_circleci.git public
                cd public
                ls
      - run:
          name: build
          command: |
                hugo
      - run:
          name: push
          command: |
              git config --global user.name "CircleCI"
              git config --global user.email "circleci@example.com"
              git add --all
              msg="rebuilding site `date`"
              git commit -m "$msg"
              git push
